---
- hosts: dev
  become: True
  tasks:
    - name: yum update
      yum:
        name: "*"
        state: latest
    - name: install the latest pip package
      pip: 
        name: pip
        state: latest
    - name: Enable EPEL Repository on CentOS 7
      yum:
        name: epel-release
        state: latest
    - name: Install python-pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker python module
      pip:
        name: docker
        state: present
        extra_args: --upgrade
        executable: pip
    - name: Start the container
      docker_container:
        name: hariapp
        image: "oistri/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
